export const rewards = {
    'data':{
        '0':[{'item':'carrot','amount':2 }],
        '1':[{'item':'carrot','amount':1 }],
        '2':[{'item':'carrot','amount':1 }],
        '3':[{'item':'carrot','amount':2 }],
        '4':[{'item':'carrot','amount':1 }],
        '5':[{'item':'bronze_egg','amount':1 }],
        '6':[{'item':'carrot','amount':1 }],
        '7':[{'item':'bronze_egg','amount':1 }],
        '8':[{'item':'carrot','amount':1 }],
        '9':[{'item':'carrot','amount':1 }],
        '10':[{'item':'silver_egg','amount':1 }],
        '11':[{'item':'carrot','amount':1 }],
        '12':[{'item':'carrot','amount':1 }],
        '13':[{'item':'carrot','amount':1 }],
        '14':[{'item':'carrot','amount':1 }],
        '15':[{'item':'silver_egg','amount':1 }],
        '16':[{'item':'carrot','amount':1,'mystery':true }],
        '17':[{'item':'carrot','amount':1 ,'mystery':true }],
        '18':[{'item':'carrot','amount':1 ,'mystery':true }],
        '19':[{'item':'carrot','amount':1,'mystery':true  }],
        '20':[{'item':'gold_egg','amount':1 }],
        '21':[{'item':'carrot','amount':1,'mystery':true }],
        '22':[{'item':'carrot','amount':1,'mystery':true  }],
        '23':[{'item':'carrot','amount':1,'mystery':true  }],
        '24':[{'item':'carrot','amount':1,'mystery':true  }],
        '25':[{'item':'bronze_egg','amount':2 }],
        '26':[{'item':'carrot','amount':1,'mystery':true }],
        '27':[{'item':'carrot','amount':1 ,'mystery':true}],
        '28':[{'item':'carrot','amount':1,'mystery':true }],
        '29':[{'item':'carrot','amount':1,'mystery':true }],
        '30':[{'item':'gold_egg','amount':1,'mystery':true },{'item':'carrot','amount':5}],

    }
}
